### ISSUE TITLE
todo-sync org /path/to/init/file.el asana $ASANA_PERSONAL_ACCESS_TOKEN error

### ISSUE THREAD

**Issue by standin000** [tmurph/todo-sync#1]
`  File "../local/lib/python2.7/site-packages/todo_sync/helpers.py", line 45
    print(title, *args, *kwargs.items(), sep="\n ", end="\n\n")
`

It seems strange, thanks!

**Comment by tmurph** [comment]
Looks like you're using python 2.7, which doesn't support "print" as a function.

Sorry, this package currently requires Python 3.  It's still alpha software and I haven't gotten around to building in Python 2.7 support.

**Comment by standin000** [comment]
thanks, tested with  python3 is OK.
